name: Backend image Build and Push

on:
  push:
    branches:
        - main
        - dev

jobs:
  prod:
    name: PROD ENV
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -t notsogaurab/backend:stable -t notsogaurab/backend:$(git rev-parse --short "$GITHUB_SHA") .
          docker push notsogaurab/backend:stable
          docker push notsogaurab/backend:$(git rev-parse --short "$GITHUB_SHA")

      - name: version increase
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          token: ${{ secrets.GH_TOKEN }}

      - name: version increase
        run: |
          git config --global user.name 'notsogaurab'
          git config --global user.email 'gauravupreti1230@gmail.com'
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "Increase package.json version"
          git push https://${{ secrets.GH_TOKEN }}@github.com/notsogaurab/gitaction-test.git
  dev:
    name: DEV ENV
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -t notsogaurab/backend:dev -t notsogaurab/backend:$(git rev-parse --short "$GITHUB_SHA") .
          docker push notsogaurab/backend:dev
          docker push notsogaurab/backend:$(git rev-parse --short "$GITHUB_SHA")